title: Home
author: Egor Shalashnikov
email: egor.shalashnikov@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  math morphology
  programming
  languages go golang c c++ python php oracle pl/sql
  arch linux plan9
  acme sam emacs
  tdd codegens
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com
twitter_username: gorro80
github_username:  egor7

markdown: kramdown
theme: minima
plugins:
  - jekyll-feed

exclude:
  - Gemfile
  - Gemfile.lock
  - node_modules
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/

sass:
  sass_dir: _sass
  style: compressed
